### ISSUE TITLE
Proposal: `redirect` helper

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/atomic-router#11]
## Idea
Core effector operators (like `sample`) are good

However, they are abstract. Which means that they don't say themselves what business logic we create. They just "connect things together"

For that, I introduced an utility called `redirect`

## Usage
```tsx
redirect({
  clock: dataSaved,
  route: successfullRoute,
  params: () => ({ ... }),
  query: () => ({ ... })
})
```
This thing is equal to:
```tsx
sample({
  clock: dataSaved,
  fn: () => ({ params: { ... }, query: { ... } }),
  target: successfulRoute.navigate
})
```

## Notes
- `params` and `query` are optional. They also can accept **stores** or **plain objects** instead
- `clock` is optional as well. If it's not passed, `redirect` returns **Event** which will open the route

**Comment by Kelin2025** [comment]
Already implemented in `0.5.0-dev.1`, created this issue just FYI

**Comment by sergeysova** [comment]
I think it is better to have method like this:

```ts
sample({
  clock,
  source,
  filter,
  fn: () => ({ params, query }),
  target: redirect({ route: routes.somePage })
})
```

**Comment by Kelin2025** [comment]
If `clock` not passed, it works this way:
```tsx
const openSmth = redirect({ route: smthRoute })
```

**Comment by Kelin2025** [comment]
Released in https://github.com/Kelin2025/atomic-router/releases/tag/v0.5.0
