### ISSUE TITLE
React components

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/atomic-router#3]
We need `Link`, `Route` and `RouterView` implementation
It's currently implemented locally on my project, but I want to polish it before publishing

**Comment by cinic** [comment]
Maybe make it a separate package? For example atomic-router-* (react, vue, forest and etc).

**Comment by Kelin2025** [comment]
Yes, of course

**Comment by Kelin2025** [comment]
Done, see [atomic-router-react](https://github.com/Kelin2025/atomic-router-react) for more info
